# Class-1(21-9-2019)
NumPy

In [1]:
import numpy as np

In [96]:
 a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [97]:
a.shape
a.ndim

1

In [98]:
2*a

array([ 2,  4,  6,  8, 10, 12])

In [99]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [100]:
b.shape

(5,)

In [101]:
b.ndim

1

In [102]:
data = np.random.randn(2,3,4)    #generats random numbers of matrix of order 2 by 3
data

array([[[-1.87627079,  1.20848522, -2.18740201,  1.11284352],
        [ 0.74951408,  1.25063962,  1.92468939,  1.04778279],
        [-2.03041651,  1.01202452,  0.79665536,  0.75107387]],

       [[ 1.02215522,  1.82574448, -0.04668715,  0.20099152],
        [-0.44268391,  1.24584255, -0.37558495,  1.53307967],
        [-0.42258503,  1.4638748 , -0.30878717, -0.41653385]]])

In [103]:
data1 = np.arange(10)

In [104]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
data1.ndim      #ndim=n dimension
                #if 1 dimension, then it is vector(vector is 1 dimensional Tensor)
                #if more than 1 dimension, it is matrix

1

In [106]:
data.ndim      # data is 2 dimension Tensor

3

In [107]:
data.shape     # order of matrix or shape of matrix

(2, 3, 4)

In [108]:
b=np.array([[[100]]]) 
b                  #more square brackets, more dimensions

array([[[100]]])

In [109]:
b.ndim

3

In [110]:
b.shape

(1, 1, 1)

In [111]:
b=np.array([[[[[[[[[[[[100]]]]]]]]]]]])

In [112]:
b.ndim

12

In [113]:
b.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [114]:
c=np.array([[1],[2]])
c

array([[1],
       [2]])

In [115]:
c.ndim

2

In [116]:
c.shape

(2, 1)

In [117]:
_3d = np.array([[[1],[4],[9],[7]]])

In [118]:
_3d

array([[[1],
        [4],
        [9],
        [7]]])

In [119]:
_3d.ndim

3

In [120]:
_3d.shape

(1, 4, 1)

In [121]:
threeD = np.arange(64).reshape(4,4,4)

In [122]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [123]:
threeD = np.arange(30).reshape(3,5,2)   #3 depth, 5 rows, 2 columns

In [38]:
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [39]:
threeD = np.arange(30).reshape(2,5,3)   #depth=2, rows=5, columns=3

In [40]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [42]:
threeD.ndim

3

In [43]:
threeD.shape

(2, 5, 3)

In [124]:
m1=np.arange(12).reshape(4,3)
m2=np.array([[1,2,3],[4,5,6],[7,8,9],[4,3,2]])

In [125]:
m1.shape == m2.shape

True

In [126]:
m1 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [127]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 3, 2]])

In [128]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 5,  7,  9]])

In [129]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [2.25      , 3.33333333, 5.5       ]])

In [130]:
m1*m2       #mirror multiplication is head to head, not the actual matrix multiplication

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [131]:
m1.shape

(4, 3)

In [132]:
m2.shape

(4, 3)

In [133]:
m3=np.arange(12).reshape(3,4)

In [134]:
m3.shape

(3, 4)

In [135]:
m1*m3         #mirror multiplication is not possible bcoz of different order

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [136]:
m1@m3                #this is actual matrix multiplication

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [71]:
print(m1.shape)           
print(m3.shape)
m1@m3

(4, 3)
(3, 4)


array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [72]:
np.dot(m1,m3)       # another way of actual multiplication

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [85]:
a = np.array([33,44,66],dtype="float32")

In [79]:
a

array([33, 44, 66])

In [80]:
a.dtype

dtype('int32')

In [140]:
b= np.array([33.4,44.66],dtype=np.float32)

In [141]:
b

array([33.4 , 44.66], dtype=float32)

In [142]:
b.dtype

dtype('float32')

In [42]:
c=np.asarray(b,np.int32)       #to change data type of existing data

In [43]:
c

array([33, 44])

In [44]:
c.dtype

dtype('int32')

In [102]:
np.ones((10,10))                #makes vector of 1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
b.dtype

dtype('float32')

In [45]:
np.zeros((3,4),dtype='int32')             #makes vector of zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [143]:
np.empty(6)          #makes array of zeros or anyother value

array([4.64e-322, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000])

In [150]:
np.ones((3,4),dtype='int32')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [152]:
np.full((3,4),5)        #it gives matrix of any desired number as in this case is 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [109]:
baaaaa = np.full((3,4),7)

In [110]:
baaaaa

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [111]:
jaaaaa = np.ones_like(baaaaa)     #it takes order and data type of baaaaa

In [112]:
jaaaaa

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [46]:
dlist = [1,2,3,4,5,6,7,8]

In [47]:
dlist[4]           #indexing gives number of that index

5

In [48]:
type(dlist)

list

In [49]:
type(dlist[4])

int

In [50]:
type(dlist[2:4])    #slicing gives list

list

In [52]:
td = np.arange(36).reshape(6,6)

In [53]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [54]:
td[2,3]          #indexing

15

In [55]:
td[2][3]            #another way of indexing

15

In [56]:
td[2:5,2:4]           #slicing

array([[14, 15],
       [20, 21],
       [26, 27]])

In [57]:
td[4:,4:]

array([[28, 29],
       [34, 35]])

# Class-2---(28-9-2019)

# Boolean Indexing

In [1]:
import numpy as np

In [8]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  #these names will be in column
                                          # these names will be converted into random numbers


In [9]:
data = np.random.randn(7, 4)


In [10]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [11]:
data

array([[-1.50517732,  0.08036097,  0.22432784, -0.45260973],
       [-0.57416439, -0.86298804, -0.67365248,  1.32187497],
       [-0.50253073,  0.56152678, -1.69847391,  1.21678753],
       [-0.63918659,  0.22041143,  0.2146394 , -0.0975564 ],
       [ 0.61976862, -0.01571529, -1.04034875,  1.03436121],
       [-0.02859841,  0.5719238 ,  1.31683937, -1.29040194],
       [ 0.5198533 ,  0.2876334 ,  0.79974439, -0.26893559]])

In [12]:
names.shape

(7,)

In [13]:
names.ndim

1

In [14]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [15]:
data[names == 'Bob']

array([[-1.50517732,  0.08036097,  0.22432784, -0.45260973],
       [-0.63918659,  0.22041143,  0.2146394 , -0.0975564 ]])

In [16]:
data[names!= 'Bob']

array([[-0.57416439, -0.86298804, -0.67365248,  1.32187497],
       [-0.50253073,  0.56152678, -1.69847391,  1.21678753],
       [ 0.61976862, -0.01571529, -1.04034875,  1.03436121],
       [-0.02859841,  0.5719238 ,  1.31683937, -1.29040194],
       [ 0.5198533 ,  0.2876334 ,  0.79974439, -0.26893559]])

In [17]:
data

array([[-1.50517732,  0.08036097,  0.22432784, -0.45260973],
       [-0.57416439, -0.86298804, -0.67365248,  1.32187497],
       [-0.50253073,  0.56152678, -1.69847391,  1.21678753],
       [-0.63918659,  0.22041143,  0.2146394 , -0.0975564 ],
       [ 0.61976862, -0.01571529, -1.04034875,  1.03436121],
       [-0.02859841,  0.5719238 ,  1.31683937, -1.29040194],
       [ 0.5198533 ,  0.2876334 ,  0.79974439, -0.26893559]])

In [18]:
data [names=='Bob' , 2:]

array([[ 0.22432784, -0.45260973],
       [ 0.2146394 , -0.0975564 ]])

In [19]:
data[names=='Bob', 1:3]

array([[0.08036097, 0.22432784],
       [0.22041143, 0.2146394 ]])

In [20]:
data[names=='Bob' , 3]

array([-0.45260973, -0.0975564 ])

In [21]:
data[~(names=='Bob')]    #  it ~ also stands for negation

array([[-0.57416439, -0.86298804, -0.67365248,  1.32187497],
       [-0.50253073,  0.56152678, -1.69847391,  1.21678753],
       [ 0.61976862, -0.01571529, -1.04034875,  1.03436121],
       [-0.02859841,  0.5719238 ,  1.31683937, -1.29040194],
       [ 0.5198533 ,  0.2876334 ,  0.79974439, -0.26893559]])

In [22]:
data[3]    #it gives third index row

array([-0.63918659,  0.22041143,  0.2146394 , -0.0975564 ])

# Fancy Indexing

In [27]:
data

array([[-1.50517732,  0.08036097,  0.22432784, -0.45260973],
       [-0.57416439, -0.86298804, -0.67365248,  1.32187497],
       [-0.50253073,  0.56152678, -1.69847391,  1.21678753],
       [-0.63918659,  0.22041143,  0.2146394 , -0.0975564 ],
       [ 0.61976862, -0.01571529, -1.04034875,  1.03436121],
       [-0.02859841,  0.5719238 ,  1.31683937, -1.29040194],
       [ 0.5198533 ,  0.2876334 ,  0.79974439, -0.26893559]])

In [28]:
data [[3,4,0,1]]    #it will look for rows, index of which given in the list

array([[-0.63918659,  0.22041143,  0.2146394 , -0.0975564 ],
       [ 0.61976862, -0.01571529, -1.04034875,  1.03436121],
       [-1.50517732,  0.08036097,  0.22432784, -0.45260973],
       [-0.57416439, -0.86298804, -0.67365248,  1.32187497]])

In [29]:
# Condition:

In [30]:
cond = names == 'Bob'

In [31]:
cond

array([ True, False, False,  True, False, False, False])

In [32]:
data[(cond)]

array([[-1.50517732,  0.08036097,  0.22432784, -0.45260973],
       [-0.63918659,  0.22041143,  0.2146394 , -0.0975564 ]])

In [35]:
data[(~cond)]

array([[-0.57416439, -0.86298804, -0.67365248,  1.32187497],
       [-0.50253073,  0.56152678, -1.69847391,  1.21678753],
       [ 0.61976862, -0.01571529, -1.04034875,  1.03436121],
       [-0.02859841,  0.5719238 ,  1.31683937, -1.29040194],
       [ 0.5198533 ,  0.2876334 ,  0.79974439, -0.26893559]])

In [36]:
#Mask

In [37]:
mask = (names == 'Bob') | (names == 'Will')     # '|' is 'or' operator

In [38]:
mask

array([ True, False,  True,  True,  True, False, False])

In [39]:
data[data <0]               # it gives the values according to the condition

array([-1.50517732, -0.45260973, -0.57416439, -0.86298804, -0.67365248,
       -0.50253073, -1.69847391, -0.63918659, -0.0975564 , -0.01571529,
       -1.04034875, -0.02859841, -1.29040194, -0.26893559])

In [48]:
data[data>0]

array([0.08036097, 0.22432784, 1.32187497, 0.56152678, 1.21678753,
       0.22041143, 0.2146394 , 0.61976862, 1.03436121, 0.5719238 ,
       1.31683937, 0.5198533 , 0.2876334 , 0.79974439])

In [49]:
data <0     # it gives Boolean result i.e True or False

array([[ True, False, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [False, False, False,  True]])

In [33]:
data > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True,  True,  True, False]])

In [52]:
x=np.arange(10).reshape(2,5)

In [57]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
x[x*0]                   #=?????????????

array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

# Fancy Indexing

In [3]:
arr = np.empty((8,4))

In [4]:
for i in range(8):
    arr[i] = i

In [5]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [6]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [7]:
arr[4]

array([4., 4., 4., 4.])

In [8]:
arr[4,:]

array([4., 4., 4., 4.])

In [9]:
arr[[4,5,6], 2:]       #Slicing

array([[4., 4.],
       [5., 5.],
       [6., 6.]])

In [10]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [11]:
arr[[1,5,7,2], [0,3,1,2]]   #it gives ordered pair

array([1., 5., 7., 2.])

In [12]:
arr = np.arange(32).reshape((8,4))

In [13]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [15]:
arr[[1,5,7,2]] [:,[0,3,1,2]]

# 1[0,3,1,2], 5[0,3,1,2], 7[0,3,1,2], 2[0,3,1,2]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing  Arrays & Swapping Axes

In [51]:
arr

array([-11.52864707,   0.96361406,  -5.62369118,   2.7657671 ,
         4.24450443,  -4.26784698,  -6.46599941])

In [52]:
arr.T

array([-11.52864707,   0.96361406,  -5.62369118,   2.7657671 ,
         4.24450443,  -4.26784698,  -6.46599941])

In [53]:
arr = np.random.randn(7) *5

In [54]:
arr

array([ 4.55797805,  8.70303824, -3.26894205, -4.25454153, 10.05765118,
       -1.02051032, 12.27471577])

In [55]:
remainder,whole_part =np.modf(arr)

In [56]:
remainder

array([ 0.55797805,  0.70303824, -0.26894205, -0.25454153,  0.05765118,
       -0.02051032,  0.27471577])

In [57]:
whole_part

array([ 4.,  8., -3., -4., 10., -1., 12.])

In [58]:
points = np.arange(-5, 5, 0.01)    #1000 equally spaced points

In [59]:
xs, ys =np.meshgrid(points, points)   #

In [60]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [61]:
points.shape


(1000,)

In [62]:
points.ndim

1

# Expressing COnditional Logic as Array Operation

In [63]:
xarr = np.array([1.1,1.2, 1.3, 1.4, 1.5])

In [64]:
yarr = np.array([2.1,2.2, 2.3, 2.4, 2.5])

In [65]:
cond = np.array([True, False, True, True, False])

In [66]:
cond

array([ True, False,  True,  True, False])

In [67]:
result = np.where(cond, xarr, yarr)

In [68]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

array([ 4.55797805,  8.70303824, -3.26894205, -4.25454153, 10.05765118,
       -1.02051032, 12.27471577])

In [69]:
arr.mean()

3.86419847548675

In [70]:
arr.sum()

27.04938932840725

In [71]:
arr.mean(axis=0)

3.86419847548675

In [72]:
arr.std()

6.252398063586781

In [74]:
arr.var()

39.09248154554373

In [75]:
arr.cumsum()

array([ 4.55797805, 13.26101629,  9.99207423,  5.73753271, 15.79518388,
       14.77467356, 27.04938933])

In [76]:
arr

array([ 4.55797805,  8.70303824, -3.26894205, -4.25454153, 10.05765118,
       -1.02051032, 12.27471577])

In [77]:
arr.argmin()    ## it gives the index of min value(not the actual value)

3

In [76]:
arr.argmax()     ## it gives the index of max value(not the actual value)

4

# Methods for Boolean Array

In [85]:
arr = np.random.randn(100)

In [86]:
arr

array([-1.83567954, -1.0282899 ,  1.70993081,  1.38597984, -0.45833   ,
        0.27020662, -0.92960131,  1.21849956,  0.20611294,  0.38471888,
       -0.33536229,  0.21870903, -0.52005303, -0.66229759,  0.35723335,
       -0.45168221, -0.9968577 , -0.03532351,  1.79518471,  0.58228882,
        1.03998441, -0.84747953,  1.15329862,  1.58644565, -0.68941086,
       -0.7429995 , -1.4345029 , -0.09108856, -0.68518191, -1.5022286 ,
        2.50199431, -0.37285869, -0.47452749, -0.44713803, -0.26019839,
       -0.63682461, -1.33295817, -2.49688901,  0.17186492, -0.38688064,
       -0.53253995, -0.88055496, -0.04778602, -0.54084541,  1.18932564,
        0.74373987, -0.88498271,  0.89272716,  0.53654453,  0.11630452,
       -0.57160722, -1.36920823, -0.07756055, -0.52285543, -0.60172514,
       -0.47279603, -1.91700287,  0.86500262,  2.48331198, -1.63246257,
        0.86036109, -0.04853771,  0.33163384, -0.76366981,  1.02720905,
        0.38087079,  1.6500977 ,  1.70365674,  0.42672   , -1.09

In [87]:
(arr>0)

array([False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False, False,  True, False, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
        True, False,  True,  True,  True, False, False, False, False,
       False, False, False,  True,  True, False,  True, False,  True,
       False,  True,  True,  True,  True,  True, False, False, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True, False, False, False, False, False, False, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True])

# Sorting

In [88]:
arr.sort()

In [90]:
arr

array([-2.89171183, -2.49688901, -2.23991007, -2.04064363, -1.91700287,
       -1.83567954, -1.63246257, -1.62355958, -1.5022286 , -1.4345029 ,
       -1.39877765, -1.36920823, -1.33295817, -1.22225764, -1.21095274,
       -1.16778004, -1.09833531, -1.0282899 , -0.9968577 , -0.99190378,
       -0.92960131, -0.88498271, -0.88055496, -0.84747953, -0.84015772,
       -0.78387669, -0.76366981, -0.7429995 , -0.68941086, -0.68518191,
       -0.66229759, -0.63682461, -0.60172514, -0.57160722, -0.54084541,
       -0.53253995, -0.52285543, -0.52005303, -0.48393034, -0.47452749,
       -0.47279603, -0.47246528, -0.45833   , -0.45168221, -0.44713803,
       -0.40391366, -0.38688064, -0.37285869, -0.33536229, -0.26019839,
       -0.22953301, -0.09108856, -0.07756055, -0.04853771, -0.04778602,
       -0.03532351, -0.01166444, -0.00404627,  0.03615224,  0.11630452,
        0.14617825,  0.17186492,  0.20611294,  0.21870903,  0.27020662,
        0.33163384,  0.35723335,  0.38087079,  0.38471888,  0.42

In [89]:
np.sort()

TypeError: sort() missing 1 required positional argument: 'a'

# Unique & Other Set Logic

In [83]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [84]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [85]:
np.unique(names)      # it removes duplicates

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [86]:
arr = np.arange(10)

In [87]:
np.save('some_array', arr)

In [90]:
np.load('some_array', arr)

FileNotFoundError: [Errno 2] No such file or directory: 'some_array'

In [91]:
from numpy.linalg import inv,qr

In [92]:
a=np.random.randn(5,5)

In [93]:
a

array([[-0.15403884,  0.09301389,  0.38496291,  0.62053357, -0.49757565],
       [ 1.96595738,  0.2372498 , -0.20686956,  0.60917664, -0.66831031],
       [ 0.50861587,  0.36526528, -1.04838822, -0.21175762, -0.42269869],
       [-0.39366988,  0.12725141, -1.22060326,  0.39228676, -0.17159659],
       [ 0.32153529,  0.51147724,  2.01632319, -1.25449617,  0.5849065 ]])

In [94]:
mat = a.T.dot(a)

In [95]:
inv(mat)

array([[ 0.52394034, -0.11704317, -0.15371727,  0.36738493,  1.13719897],
       [-0.11704317,  9.30903627, -0.44367906,  5.41885951,  7.34996864],
       [-0.15371727, -0.44367906,  0.32921996, -0.20669053, -0.88463623],
       [ 0.36738493,  5.41885951, -0.20669053,  4.77033488,  6.4771209 ],
       [ 1.13719897,  7.34996864, -0.88463623,  6.4771209 , 11.07472591]])

In [96]:
mat.dot(inv(mat))       

array([[ 1.00000000e+00,  0.00000000e+00,  2.22044605e-16,
         0.00000000e+00,  0.00000000e+00],
       [-1.24900090e-16,  1.00000000e+00,  9.71445147e-17,
        -2.22044605e-16, -2.10942375e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         3.55271368e-15,  3.55271368e-15],
       [-2.22044605e-16,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00]])

In [184]:
arr = np.arange(15)

In [185]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [186]:
arr.reshape(5,-1)    #i should be (5,3), but -1, takes second argument itself i.e 3 in this case

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [187]:
ravel = arr.ravel()

In [188]:
flat = arr.flatten()

In [189]:
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [190]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [191]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [192]:
flat[2:8] =0

In [193]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [198]:
ravel[2:8] =0

In [199]:
flat

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [201]:
ravel

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

# Concatenating and Splitting Arrays

In [110]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [111]:
arr2 = np.array([[7,8,9],[10,11,12]])

In [112]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [114]:
np.concatenate([arr1,arr2])      #concatenating downward i.e increasing rows or two arrays added horizontally

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [115]:
np.concatenate([arr1,arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [117]:
np.concatenate([arr1,arr2], axis=1)     #arrays added to column or two arrays added horizontally

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [119]:
np.vstack((arr1,arr2))      #vertical stack, added vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [121]:
np.hstack((arr1,arr2))       #horizontal stack, added horizontally

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [123]:
np.vsplit(split,3)

NameError: name 'split' is not defined

In [202]:
arr.repeat(3)           #repeats each member three times

array([ 0,  0,  0,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14])

In [203]:
np.tile(arr,2)

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14,  0,  1,
        0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [204]:
arr

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [205]:
#Broadcasting

In [206]:
arr=np.array([1,2,3,4])
a=np.broadcast(arr,4)

In [207]:
a

# Q2-AI-Class#3(5-10-2019)

In [1]:
import numpy as np

In [5]:
arr3d=np.arange(50).reshape(5,5,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [6]:
arr3d=np.arange(50).reshape(2,5,5)       #(2,5,5) means (depth,row,colums)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [7]:
arr3d[1,2,3]          #indexing

38

In [8]:
arr3d[0,3,4]

19

In [9]:
arr3d[1,2:,1:3]

array([[36, 37],
       [41, 42],
       [46, 47]])

In [11]:
arr3d[0,2:4,4:]       #gives 2 dimensional matrix
                      #bcoz there are three parameters and start and end of two parameters is given

array([[14],
       [19]])

In [12]:
arr3d[0,2:4,4]      #give 1 dimensional matrix
                    #bcoz there are three parameters and start and end of one parameter is given

array([14, 19])

In [13]:
arr3d[0:1,2:,4:]       #give 3 dimensional matrix
                       #bcoz there are three parameters and start and end of thtee parameters is given

array([[[14],
        [19],
        [24]]])

In [14]:
arr3d[0:1,2:,4]

array([[14, 19, 24]])

In [15]:
arr3d[0:,0:,0]

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

# practice

In [4]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [5]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arr3d.shape

(2, 2, 3)

In [7]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
arr3d[1,0]

array([7, 8, 9])

In [10]:
arr3d[1,1]

array([10, 11, 12])

In [12]:
arr3d[0,1]

array([4, 5, 6])

In [168]:
_arr=np.arange(32).reshape(16,2)

In [169]:
_arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [171]:
first, second, third = np.split(_arr, [1,3])

In [165]:
first

array([[0, 1]])

In [166]:
second

array([[2, 3],
       [4, 5]])

In [167]:
third

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [177]:
np.vsplit(_arr,4)

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]), array([[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]), array([[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]])]

In [178]:
arr1=np.arange(32).reshape(4,8)

In [179]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [183]:
np.hsplit(arr1,4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]), array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]), array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]), array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]